image: node:16

definitions:
  steps:
    - step: &test
        caches:
          - node
        name: test
        script:
          - mv .npmrc_config .npmrc
          - yarn install --production=false
          - yarn build
          - yarn test:types
          - yarn test:lint
          - yarn test:unit --ci

    - step: &publish
        name: publish
        script:
          - mv .npmrc_config .npmrc
          - yarn install --production=false
          - yarn build
          - yarn publish --tag $BITBUCKET_TAG

pipelines:
  branches:
    master:
      - step: *test

  pull-requests:
    "**":
      - step: *test

  tags:
    "**":
      - step: *test
      - step: *publish
